### PR TITLE
clarkson

### PR DESCRIPTION
**Pull request by CHBMB**
Needs support thread

### CODE REVIEW

**Comment by tobbenb** [comment]
Should we maybe add that a database named clarkson must be made in mariadb/MySQL?

**Comment by CHBMB** [comment]
It has to be MySQL, it's not MariaDB compatible.

**Comment by tobbenb** [comment]
It creates by itself with MySQL?

**Comment by CHBMB** [comment]
No, it does need the database creating first.  I'll add a note.

**Comment by CHBMB** [comment]
@tobbenb Added a note and also added info about required MySQL version.

**Review by tobbenb — APPROVED** [review]

**Comment by tobbenb** [comment]
Good lad!

**Pull request merged**
