### PR TITLE
calibre-web template

### PR DESCRIPTION
**Pull request by CHBMB**
Needs support thread.

### CODE REVIEW

**Review by aptalca — APPROVED** [review]

**Comment by CHBMB** [comment]
Why is this closed @sparklyballs?

**Comment by sparklyballs** [comment]
doesn't work on unraid that is ipv4 only

**Comment by CHBMB** [comment]
Works on V6.4.  We can tag it in CA as such.

**Comment by sparklyballs** [comment]
6.4 is not released though.

**Comment by CHBMB** [comment]
People are running it, and it will be released.  So I don't see the issue.  Tagged as V6.4 only there's no problem.

**Comment by sparklyballs** [comment]
but it isn't released.....

**Comment by CHBMB** [comment]
People are running the release candidate and even if we wait until final, which I don't think is necessary, I don't see the need to close the PR.  Regardless of whether we wait for v6.4 final or not, the issue will remain that it will need to be tagged for v6.4, as they'll be a ton of people who won't upgrade.

**Comment by sparklyballs** [comment]
keeping the branch is preferable to a perpetually open PR waiting for a mythical release.

**Comment by CHBMB** [comment]
I'll sort out the tag for version and it could be merged, I don't see why we need to be beholden to LT's release strategy to release a container that people using the RC could quite happily use.

**Comment by sparklyballs** [comment]
it's enough to support images on hosts with stable releases let alone on ever shifting rc's

**Comment by CHBMB** [comment]
Well this app has had a more thorough than most test run, seeing as I'm using it and have been for a long while.

**Pull request closed without merging**
