### PR TITLE
Proper template

### PR DESCRIPTION
**Pull request by Squidly271**
Network bridge more or less worked by accident.  This is the proper xml, generated by dockerMan.

### CODE REVIEW

**Review by CHBMB — APPROVED** [review]

**Comment by tobbenb** [comment]
Closing as it had conflicts. Made the change in another PR.

**Comment by Squidly271** [comment]
Well,what do you expect when you sit on a pr for 9 months

**Comment by tobbenb** [comment]
The doctor could have merged it also... Hopefully it didn't break the app feed!

**Comment by Squidly271** [comment]
The appfeed is unbreakable now :)   And added a new "trending" item so you guys can tell at a glance how popular a container is since DL counts aren't really a good metric because you issue weekly updates

**Comment by tobbenb** [comment]
I'll try to break it ;p

**Pull request closed without merging**
