### PR TITLE
<TemplateURL> Support

### PR DESCRIPTION
**Pull request by CHBMB**
So, after a discussion with @jlesage adding this will mean that changes to the XML will be pushed to the user, providing it doesn't impair their current config.

Example use cases would be ubooquity, adding the new port required.  And documentation changes.

@Squidly271 Happy with this?  Care to elaborate?

### CODE REVIEW

**Comment by sparklyballs** [comment]
doesn't help make me a cup of coffee

blah

**Comment by CHBMB** [comment]
It never claimed to you grumpy git!

**Comment by sparklyballs** [comment]
fine !!!!

go ahead and ignore the issue

**Comment by CHBMB** [comment]
:coffee: There you go, now shut up about the damn coffee.

**Comment by Squidly271** [comment]
How did I get dragged into this?   Did you do all your due diligence and test the changes and the modify templates and test again?    I could just be pulling your chain for my own nefarious reasons

**Comment by CHBMB** [comment]
@Squidly271 That would be a dick move, you're Canadian, you're nice....

**Comment by Squidly271** [comment]
Just because I'm polite doesn't mean that I can't have fun at someone's expense.

**Pull request merged**
