### PR TITLE
Change logo to the correct one for habridge

### LINKED ISSUE #7: Do not use Home Assistant logo for habridge inside Unraid Community Applications
To avoid confusion, please do not use the Home Assistant logo for other products.

This is the current screenshot from Unraid Community Applications:
image

### PR DESCRIPTION
**Pull request by tobbenb**
fixes linuxserver/docker-habridge#7

### CODE REVIEW

**Review by CHBMB — CHANGES_REQUESTED** [review]
Can we add the new one so it's all within our repository, rather than pulling from an external source?

**Comment by CHBMB** [comment]
Also, that icon is going to look like shit on Unraid

**Comment by tobbenb** [comment]
That is the official icon, and the only one available. So there are no better icons. 
Does it matter if it's on the upstreams github?

**Comment by tobbenb** [comment]
Better now?

**Review by CHBMB — APPROVED** [review]

**Pull request merged**
