### PR TITLE
Booksonic template...

### PR DESCRIPTION
**Pull request by CHBMB**
Needs date and support thread updating....

### CODE REVIEW

**Comment by sparklyballs** [comment]
there's no PGID or PUID variables

**Comment by sparklyballs** [comment]
that's just on first glance, i'm sure there's other stuff missing.

**Comment by CHBMB** [comment]
Yeah there is: https://github.com/CHBMB/docker-templates/blob/master/linuxserver.io/booksonic.xml

**Comment by CHBMB** [comment]
Support thread done.

**Pull request merged**
